[Paths]
# ใช้ {year} เพื่อเปลี่ยนปีอัตโนมัติ
base_source_dir_Prod = O:\!!!!จ่ายจบหนี้คืนรถจบหนี้ {year}\2.MIS_ROUND1 Add Data
base_source_dir = D:\80011256\01-GJ_Project\07-CLD_Blacklist_TypeO\!!!!จ่ายจบหนี้คืนรถจบหนี้ {year}\2.MIS_ROUND1 Add Data

dest_dir = D:\80011256\01-GJ_Project\07-CLD_Blacklist_TypeO\Destination
dest_filename = Add_Blacklist_CLD.xlsx

[Sheets]
sheet1_name = จ่ายจบหนี้
sheet1_remark = ลูกค้าใช้สิทธิเข้าโครงการจ่ายจบหนี้ ได้รับส่วนลดปิดบัญชี
sheet2_name = คืนจบหนี้
sheet2_remark = ลูกค้าใช้สิทธิเข้าโครงการคืนรถจบหนี้ ได้รับส่วนลดปิดบัญชี





[MailConfig]
smtp_server = 10.45.1.25
smtp_port = 25
mail_from = Noreply_CLD-TechProcess@tidlor.com
mail_to_prod = user1@yourcompany.com, user2@yourcompany.com
mail_to = suwimol.t@tidlor.com
mail_cc = suwimol.t@tidlor.com
signature =  
    Thanks and Regards,
    หากมีคำถามเพิ่มเติม กรุณาติดต่อทีม Collection Tech : CLD-TechProcess@tidlor.com
    📌 This is an automated email by [RPA-XXXXXXX] 📌


[MailTemplates]
success_subject = [Success][Service-CLDTECH][Process Blacklist] รายงานผลการ ประจำวันที่ {date}
success_body = เรียน ทีมงานที่เกี่ยวข้อง
    
    ระบบได้ทำการรันไฟล์ {source_filename} เรียบร้อยแล้ว
    - ข้อมูลต้นทางทั้งหมด: {total_source} รายการ
    - ข้อมูลที่ Generate ลงไฟล์ปลายทาง: {total_dest} รายการ
    - นำไปวางไว้ที่: {dest_path}
    
    จึงเรียนมาเพื่อโปรดทราบ

missing_source_subject = [Error][Service-CLDTECH][Process Blacklist]  ไม่พบไฟล์ต้นทางจาก MIS ประจำวันที่ {date}
missing_source_body = เรียน ทีมงานที่เกี่ยวข้อง
    
    ระบบไม่พบไฟล์ต้นทางที่ Path:
    {source_path}
    
    จึงเรียนมาเพื่อโปรดตรวจสอบและนำไฟล์ไปวางให้ครบถ้วน

empty_source_subject = [Warning][Service-CLDTECH][Process Blacklist] ไฟล์ต้นทางไม่มีข้อมูล ประจำวันที่ {date}
empty_source_body = เรียน ทีมงานที่เกี่ยวข้อง
    
    ระบบพบไฟล์ต้นทาง {source_filename} แต่ไม่มีข้อมูลใน Sheet ที่กำหนด
    ระบบจึงไม่ได้ทำการ Generate ไฟล์ปลายทาง
    
    จึงเรียนมาเพื่อโปรดทราบ

error_dest_subject = [Error][Service-CLDTECH][Process Blacklist] ไม่สามารถวางไฟล์ปลายทางได้ ประจำวันที่ {date}
error_dest_body = เรียน ทีมงานที่เกี่ยวข้อง
    
    ระบบอ่านข้อมูลสำเร็จ ({total_dest} รายการ) แต่ไม่สามารถบันทึกไฟล์ปลายทางได้
    Path: {dest_path}
    
    Error: {error_detail}
    
    โปรดตรวจสอบว่ามีคนเปิดไฟล์ค้างไว้ หรือ Network Drive มีปัญหาหรือไม่
